const projects = [
  { id:'andaman', name:'Andaman Mangrove Restoration', shortName:'Andaman', provinces:'Krabi · Phang Nga · Phuket · Ranong · Satun', plots:18, areaRai:3240, monitoring:82, mrv:76, carbonTarget:21800, carbonForecast:19600, criticalRisks:2, nextMilestone:'Monitoring cycle close', milestoneDays:18, status:'Attention' },
  { id:'samutsongkhram', name:'Samut Songkhram Blue Carbon', shortName:'Samut Songkhram', provinces:'Samut Songkhram', plots:8, areaRai:1460, monitoring:71, mrv:64, carbonTarget:12100, carbonForecast:10350, criticalRisks:2, nextMilestone:'MRV evidence review', milestoneDays:11, status:'At risk' },
  { id:'rayong', name:'Rayong Coastal Restoration', shortName:'Rayong', provinces:'Rayong', plots:6, areaRai:980, monitoring:88, mrv:84, carbonTarget:8400, carbonForecast:8050, criticalRisks:1, nextMilestone:'Field verification', milestoneDays:24, status:'On track' },
  { id:'maeklong', name:'Mae Klong Community Forestry', shortName:'Mae Klong', provinces:'Samut Sakhon · Samut Songkhram', plots:6, areaRai:1210, monitoring:69, mrv:72, carbonTarget:9700, carbonForecast:8750, criticalRisks:0, nextMilestone:'Reviewer sign-off', milestoneDays:31, status:'Attention' },
]

const risks = [
  { id:'R-014', projectId:'samutsongkhram', scope:'51-STC', title:'Survival ต่ำกว่าเป้าหมายและต้องยืนยันสาเหตุ', category:'Ecological', severity:'Critical', confidence:'High', likelihood:4, impact:5, owner:'Field Manager', due:'22 Sep', trend:'up', status:'Mitigating', source:'Field + growth monitoring', action:'ลงพื้นที่ยืนยัน root cause และกำหนดมาตรการปลูกซ่อม' },
  { id:'R-017', projectId:'samutsongkhram', scope:'Project', title:'หลักฐาน MRV ยังไม่ครบก่อนรอบตรวจ', category:'MRV / Data', severity:'High', confidence:'High', likelihood:4, impact:4, owner:'MRV Lead', due:'20 Sep', trend:'up', status:'Open', source:'Evidence readiness rules', action:'ปิด evidence gap และ reviewer backlog ก่อน freeze รอบข้อมูล' },
  { id:'R-021', projectId:'andaman', scope:'81-STC', title:'ผลการเติบโตต่ำเมื่อเทียบกลุ่ม pilot', category:'Ecological', severity:'High', confidence:'Medium', likelihood:3, impact:4, owner:'Ecology Analyst', due:'25 Sep', trend:'flat', status:'Monitoring', source:'Growth check', action:'ตรวจเทียบ field condition, water level และ substrate' },
  { id:'R-025', projectId:'andaman', scope:'73-STC', title:'แนวชายฝั่งต้องติดตามหลังสัญญาณการเปลี่ยนแปลง', category:'Climate / Physical', severity:'Medium', confidence:'Medium', likelihood:3, impact:3, owner:'GIS Lead', due:'30 Sep', trend:'flat', status:'Monitoring', source:'Satellite change screen', action:'ติดตามภาพรอบถัดไปและเทียบ shoreline / vegetation edge' },
  { id:'R-031', projectId:'rayong', scope:'Project', title:'ข้อมูลน้ำขึ้นลงอาจทำให้ภาพ monitoring บางรอบเทียบกันคลาดเคลื่อน', category:'MRV / Data', severity:'Medium', confidence:'High', likelihood:3, impact:3, owner:'Remote Sensing Lead', due:'28 Sep', trend:'down', status:'Mitigating', source:'Tide + satellite review', action:'ใช้ acquisition window และ tide metadata ประกอบการคัด scene' },
  { id:'R-034', projectId:'maeklong', scope:'Project', title:'Monitoring progress ต่ำกว่าแผนรายเดือน', category:'Operational', severity:'Medium', confidence:'High', likelihood:3, impact:3, owner:'Project Manager', due:'24 Sep', trend:'up', status:'Open', source:'Schedule variance', action:'จัดลำดับแปลงค้างและกำหนด owner ต่อรอบลงพื้นที่' },
]

const decisions = [
  { id:'D-008', projectId:'samutsongkhram', title:'อนุมัติ field verification สำหรับ 51-STC', why:'ความเสี่ยง ecological อยู่ระดับ Critical และข้อมูลปัจจุบันชี้ว่าควรยืนยัน root cause ก่อนกำหนด treatment', severity:'Critical', evidence:['Field: abnormal','Growth: weak','Drone: available'], recommendation:'ลงพื้นที่ภายใน 7 วันและบันทึก cause + treatment candidate', owner:'Executive / PM', due:'Today' },
  { id:'D-011', projectId:'samutsongkhram', title:'เร่งปิด MRV evidence gap ก่อนรอบ review', why:'MRV readiness อยู่ต่ำกว่าระดับที่ควรใช้เข้าสู่รอบตรวจ และมีรายการค้างที่กระทบ timeline', severity:'High', evidence:['Evidence: partial','Review: pending','Monitoring: 71%'], recommendation:'เพิ่ม reviewer capacity ชั่วคราวและ freeze รายการที่ผ่านแล้ว', owner:'MRV Lead', due:'2 days' },
  { id:'D-014', projectId:'andaman', title:'กำหนดแผนตรวจซ้ำ 81-STC', why:'Growth check ต่ำกว่ากลุ่มเปรียบเทียบ แต่ confidence ยังไม่พอสำหรับ remediation โดยตรง', severity:'High', evidence:['Growth: weak','Field: mixed','Satellite: no critical alert'], recommendation:'เก็บ field evidence เพิ่มก่อนตัดสินใจปลูกซ่อม', owner:'Project Manager', due:'5 days' },
  { id:'D-019', projectId:'maeklong', title:'จัดลำดับแปลง monitoring ที่ค้าง', why:'Progress ต่ำกว่าแผนและเริ่มกระทบความสดใหม่ของข้อมูลที่จะใช้สรุประดับโครงการ', severity:'Medium', evidence:['Monitoring: 69%','MRV: 72%','Critical risks: 0'], recommendation:'เร่งเฉพาะ plot ที่ข้อมูล stale และมี milestone ใกล้ก่อน', owner:'Operations Lead', due:'7 days' },
]

const readiness = {
  samutsongkhram:[['Project boundary & baseline','Ready','ขอบเขตและ baseline พร้อมใช้งาน'],['Monitoring events','Partial','บางแปลงยังไม่ครบ cycle ล่าสุด'],['Field evidence','Partial','ต้องเติม evidence สำหรับรายการเสี่ยง'],['Drone / imagery evidence','Ready','มี asset และ revision อ้างอิง'],['Analysis review','Partial','มีรายการ pending reviewer'],['Risk assessment','Action','มี 2 risk ระดับ High/Critical'],['Mitigation evidence','Missing','ยังไม่ปิด treatment ของ R-014'],['GHG / carbon calculation','Partial','ใช้ค่า forecast สำหรับ MVP'],['Verification package','Partial','ยังไม่พร้อม freeze package']],
  andaman:[['Project boundary & baseline','Ready','พร้อม'],['Monitoring events','Ready','coverage สูง'],['Field evidence','Partial','81-STC ต้องตรวจเพิ่ม'],['Drone / imagery evidence','Ready','พร้อม'],['Analysis review','Ready','พร้อม'],['Risk assessment','Partial','เปิด 2 risk'],['Mitigation evidence','Partial','ติดตาม 81-STC'],['GHG / carbon calculation','Partial','forecast only'],['Verification package','Partial','รอ cycle close']],
  rayong:[['Project boundary & baseline','Ready','พร้อม'],['Monitoring events','Ready','88%'],['Field evidence','Ready','พร้อม'],['Drone / imagery evidence','Ready','พร้อม'],['Analysis review','Ready','พร้อม'],['Risk assessment','Ready','เหลือ risk ระดับ Medium'],['Mitigation evidence','Ready','มีมาตรการ tide-screening'],['GHG / carbon calculation','Partial','forecast only'],['Verification package','Partial','รอ milestone ถัดไป']],
  maeklong:[['Project boundary & baseline','Ready','พร้อม'],['Monitoring events','Partial','progress 69%'],['Field evidence','Partial','รอรอบลงพื้นที่'],['Drone / imagery evidence','Ready','พร้อม'],['Analysis review','Partial','รอ reviewer sign-off'],['Risk assessment','Ready','ไม่มี critical risk'],['Mitigation evidence','Ready','ไม่มีรายการ critical'],['GHG / carbon calculation','Partial','forecast only'],['Verification package','Partial','รอ monitoring complete']],
}

const state = { nav:'overview', project:'samutsongkhram', severity:'All', category:'All', reviewed:new Set(), mobile:false }
const severityRank = { Critical:4, High:3, Medium:2, Low:1 }
const navItems = [ ['overview','01','Executive Overview'],['projects','02','Projects'],['risks','03','Risk Center'],['decisions','04','Decision Center'],['mrv','05','MRV Readiness'] ]
const fmt = n => new Intl.NumberFormat('th-TH').format(n)
const cls = s => `severity severity-${s.toLowerCase()}`
const statusPill = s => `<span class="status-pill status-${s.toLowerCase().replace(' ','-')}">${s}</span>`
const metricCard = (label,value,meta,tone='neutral') => `<div class="metric-card metric-${tone}"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-meta">${meta}</div></div>`

function progressRow(label, actual, target, forecast, unit='%') {
  const actualPct = Math.min(100, Math.max(0, actual / target * 100))
  const forecastPct = forecast == null ? null : Math.min(100, Math.max(0, forecast / target * 100))
  return `<div class="progress-row"><div class="progress-head"><div><strong>${label}</strong><span>Target ${fmt(target)}${unit}</span></div><div class="progress-number">${fmt(actual)}${unit}</div></div><div class="progress-track"><div class="progress-actual" style="width:${actualPct}%"></div>${forecastPct == null ? '' : `<div class="progress-forecast" style="left:calc(${forecastPct}% - 2px)" title="Forecast ${forecast}${unit}"></div>`}</div>${forecast == null ? '' : `<div class="progress-caption">Forecast ${fmt(forecast)}${unit} · variance ${forecast-target >= 0 ? '+' : ''}${fmt(forecast-target)}${unit}</div>`}</div>`
}

function riskMatrix(items) {
  let cells = ''
  for (let impact = 5; impact >= 1; impact--) {
    for (let l = 1; l <= 5; l++) {
      const score = l * impact
      const tone = score >= 16 ? 'critical' : score >= 10 ? 'high' : score >= 5 ? 'medium' : 'low'
      const count = items.filter(r => r.likelihood === l && r.impact === impact).length
      cells += `<div class="matrix-cell matrix-${tone}">${count ? `<span>${count}</span>` : ''}</div>`
    }
  }
  return `<div class="risk-matrix-wrap"><div class="risk-axis-label y">Impact</div><div class="risk-matrix">${cells}</div><div class="risk-axis-label x">Likelihood →</div></div><div class="risk-legend"><span><i class="legend low"></i>Low</span><span><i class="legend medium"></i>Medium</span><span><i class="legend high"></i>High</span><span><i class="legend critical"></i>Critical</span></div>`
}

function shell(content) {
  const title = { overview:'Overview', projects:'Projects', risks:'Risk Center', decisions:'Decisions', mrv:'MRV Readiness' }[state.nav]
  return `<div class="app-shell"><aside class="sidebar ${state.mobile ? 'open' : ''}"><div class="brand"><div class="brand-mark">FC</div><div><strong>Forest Carbon</strong><span>Command Center</span></div></div><nav>${navItems.map(([k,c,l]) => `<button data-nav="${k}" class="${state.nav===k?'active':''}"><span>${c}</span>${l}</button>`).join('')}</nav><div class="sidebar-note"><small>STATUS</small><strong>MVP prototype</strong><span>Demo data · no backend</span></div></aside><div class="content-shell"><header class="topbar"><button id="menu" class="menu-button">☰</button><div><span>Forest carbon portfolio</span><strong>${title}</strong></div><div class="top-actions"><span class="live-dot"></span>Demo mode<div class="avatar">EX</div></div></header><main>${content}</main></div></div>`
}

function overview() {
  const totalArea = projects.reduce((s,p)=>s+p.areaRai,0)
  const totalTarget = projects.reduce((s,p)=>s+p.carbonTarget,0)
  const totalForecast = projects.reduce((s,p)=>s+p.carbonForecast,0)
  const avgMonitoring = Math.round(projects.reduce((s,p)=>s+p.monitoring,0)/projects.length)
  const avgMrv = Math.round(projects.reduce((s,p)=>s+p.mrv,0)/projects.length)
  const highRisk = risks.filter(r=>severityRank[r.severity]>=3).length
  const topRisks = [...risks].sort((a,b)=>severityRank[b.severity]-severityRank[a.severity]).slice(0,4)
  return `<div class="page-heading"><div><div class="eyebrow">EXECUTIVE OVERVIEW</div><h1>Forest Carbon Command Center</h1><p>ภาพรวมผลการดำเนินงาน ความพร้อม MRV และความเสี่ยงที่ต้องการการตัดสินใจ</p></div><div class="asof">As of 17 Sep 2026<div>Data freshness: mixed</div></div></div>
  <div class="demo-banner"><strong>MVP / ASSUMED DATA</strong><span>ตัวเลข Carbon, target, timeline และ risk บางรายการเป็นข้อมูลสมมติเพื่อทดสอบรูปแบบการตัดสินใจ — ข้อมูลจริงต้องเชื่อมจาก source system ภายหลัง</span></div>
  <div class="metric-grid">${metricCard('Projects',projects.length,`${projects.reduce((s,p)=>s+p.plots,0)} plots · ${fmt(totalArea)} rai`)}${metricCard('Monitoring complete',`${avgMonitoring}%`,'portfolio MVP view','warning')}${metricCard('Carbon forecast',`${fmt(totalForecast)} tCO₂e`,`${fmt(totalTarget)} target · ${Math.round(totalForecast/totalTarget*100)}% of target`,'warning')}${metricCard('High / Critical risks',highRisk,`${risks.length} open risks total`,'danger')}${metricCard('Decisions pending',decisions.length,'executive / PM attention','danger')}${metricCard('MRV readiness',`${avgMrv}%`,'portfolio average','warning')}</div>
  <div class="two-col main-grid"><section class="panel"><div class="panel-head"><div><h2>Performance vs target</h2><p>ดู actual, forecast และ variance ในจุดเดียว</p></div><button class="text-button" data-nav="projects">ดูทุกโครงการ</button></div>${progressRow('Monitoring completion',avgMonitoring,100,91)}${progressRow('MRV readiness',avgMrv,100,88)}${progressRow('Carbon forecast',totalForecast,totalTarget,totalForecast,' tCO₂e')}${progressRow('Executive actions closed',68,100,79)}</section>
  <section class="panel attention-panel"><div class="panel-head"><div><h2>Needs attention</h2><p>เรียงจากเรื่องที่ควรตัดสินใจก่อน</p></div><button class="text-button" data-nav="decisions">Decision center</button></div><div class="attention-list">${topRisks.map(r=>{const p=projects.find(x=>x.id===r.projectId);return `<button class="attention-item" data-project="${r.projectId}"><span class="${cls(r.severity)}">${r.severity}</span><div><strong>${r.scope} · ${r.title}</strong><span>${p.shortName} · ${r.source}</span></div><span class="attention-arrow">›</span></button>`}).join('')}</div></section></div>
  <div class="two-col secondary-grid"><section class="panel"><div class="panel-head"><div><h2>Portfolio risk exposure</h2><p>Likelihood × Impact ของ open risks</p></div><button class="text-button" data-nav="risks">Risk center</button></div>${riskMatrix(risks)}</section><section class="panel"><div class="panel-head"><div><h2>Project health by dimension</h2><p>ไม่รวมเป็นคะแนนเดียว เพื่อไม่ซ่อนปัญหา</p></div></div><div class="dimension-table"><div class="dimension-row header"><span>Project</span><span>Ops</span><span>Eco</span><span>Carbon</span><span>MRV</span></div>${projects.map(p=>`<button class="dimension-row" data-project="${p.id}"><span>${p.shortName}</span><span class="dot ${p.monitoring>=80?'green':p.monitoring>=70?'amber':'red'}"></span><span class="dot ${p.criticalRisks===0?'green':p.criticalRisks===1?'amber':'red'}"></span><span class="dot ${p.carbonForecast/p.carbonTarget>=.95?'green':p.carbonForecast/p.carbonTarget>=.85?'amber':'red'}"></span><span class="dot ${p.mrv>=80?'green':p.mrv>=70?'amber':'red'}"></span></button>`).join('')}</div></section></div>
  <section class="panel portfolio-panel"><div class="panel-head"><div><h2>Portfolio</h2><p>จากระดับบริหาร drill-down ไปยัง project / plot / evidence</p></div></div><div class="table-wrap"><table><thead><tr><th>Project</th><th>Status</th><th>Monitoring</th><th>MRV</th><th>Carbon forecast</th><th>Critical risks</th><th>Next milestone</th></tr></thead><tbody>${projects.map(p=>`<tr data-project="${p.id}"><td><strong>${p.name}</strong><span class="cell-sub">${p.provinces}</span></td><td>${statusPill(p.status)}</td><td>${p.monitoring}%</td><td>${p.mrv}%</td><td>${fmt(p.carbonForecast)} <span class="muted">/ ${fmt(p.carbonTarget)}</span></td><td>${p.criticalRisks}</td><td>${p.nextMilestone}<span class="cell-sub">in ${p.milestoneDays} days</span></td></tr>`).join('')}</tbody></table></div></section>`
}

function projectsView() {
  const project = projects.find(p=>p.id===state.project) || projects[0]
  const pr = risks.filter(r=>r.projectId===project.id)
  return `<div class="page-heading"><div><div class="eyebrow">PROJECTS</div><h1>Project performance</h1><p>Target → Actual → Forecast พร้อมความเสี่ยงและ milestone</p></div></div><div class="project-tabs">${projects.map(p=>`<button class="${p.id===project.id?'active':''}" data-select-project="${p.id}">${p.shortName}<span>${p.status}</span></button>`).join('')}</div>
  <section class="project-hero panel"><div><div class="eyebrow">PROJECT COCKPIT</div><h2>${project.name}</h2><p>${project.provinces} · ${project.plots} plots · ${fmt(project.areaRai)} rai</p></div>${statusPill(project.status)}</section>
  <div class="metric-grid four">${metricCard('Monitoring',`${project.monitoring}%`,'current cycle',project.monitoring>=80?'good':'warning')}${metricCard('MRV readiness',`${project.mrv}%`,'evidence + review',project.mrv>=80?'good':'warning')}${metricCard('Carbon forecast',fmt(project.carbonForecast),`${fmt(project.carbonTarget)} tCO₂e target`,'warning')}${metricCard('Open risks',pr.length,`${pr.filter(r=>severityRank[r.severity]>=3).length} high / critical`,pr.some(r=>r.severity==='Critical')?'danger':'warning')}</div>
  <div class="two-col main-grid"><section class="panel"><div class="panel-head"><div><h2>Project timeline</h2><p>สถานะสำคัญระดับโครงการ</p></div></div><div class="timeline">${[['Baseline & boundary','complete'],['Monitoring cycle','active'],['Risk treatment','active'],['MRV evidence freeze','next'],['Verification','future'],['Issuance / reporting','future']].map(([t,s],i)=>`<div class="timeline-item ${s}"><div class="timeline-node">${i+1}</div><div><strong>${t}</strong><span>${s==='complete'?'Completed':s==='active'?'In progress':s==='next'?`${project.milestoneDays} days to next gate`:'Upcoming'}</span></div></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><div><h2>Open risks</h2><p>Risk → owner → treatment</p></div></div><div class="risk-card-list">${pr.length?pr.map(r=>`<div class="compact-risk"><div><span class="${cls(r.severity)}">${r.severity}</span><strong>${r.id} · ${r.title}</strong></div><p>${r.scope} · ${r.owner} · due ${r.due}</p><div class="risk-action">${r.action}</div></div>`).join(''):'<div class="empty">No open risks in MVP data.</div>'}</div></section></div>
  <section class="panel"><div class="panel-head"><div><h2>Evidence storyline</h2><p>ตัวอย่างการเชื่อมจาก management view ไป operational evidence</p></div></div><div class="evidence-flow"><div><span>1</span><strong>Monitoring signal</strong><p>Satellite / drone / field / schedule</p></div><b>→</b><div><span>2</span><strong>Assessment</strong><p>severity + confidence + cause</p></div><b>→</b><div><span>3</span><strong>Decision</strong><p>approve / investigate / defer</p></div><b>→</b><div><span>4</span><strong>Action & follow-up</strong><p>owner + due + residual risk</p></div></div></section>`
}

function riskCenter() {
  const cats = ['All', ...new Set(risks.map(r=>r.category))]
  const filtered = risks.filter(r=>(state.severity==='All'||r.severity===state.severity)&&(state.category==='All'||r.category===state.category))
  return `<div class="page-heading"><div><div class="eyebrow">RISK CENTER</div><h1>Portfolio risk register</h1><p>แยก severity, confidence, owner และ treatment — ไม่ใช้สีเดียวแทนทุกอย่าง</p></div></div><div class="toolbar"><div class="segmented">${['All','Critical','High','Medium','Low'].map(s=>`<button data-severity="${s}" class="${state.severity===s?'active':''}">${s}</button>`).join('')}</div><select id="category">${cats.map(c=>`<option ${state.category===c?'selected':''}>${c}</option>`).join('')}</select></div><div class="two-col risk-layout"><section class="panel"><div class="panel-head"><div><h2>Exposure matrix</h2><p>${filtered.length} risks in current filter</p></div></div>${riskMatrix(filtered)}</section><section class="panel"><div class="panel-head"><div><h2>Risk controls</h2><p>ข้อมูลที่ต้องมีใน risk record</p></div></div><div class="control-list"><span>Likelihood</span><span>Impact</span><span>Spatial scope</span><span>Evidence confidence</span><span>Owner</span><span>Treatment</span><span>Due date</span><span>Residual risk</span></div></section></div><section class="panel"><div class="table-wrap"><table class="risk-table"><thead><tr><th>Risk</th><th>Category</th><th>Severity</th><th>Confidence</th><th>L×I</th><th>Owner</th><th>Due</th><th>Status</th></tr></thead><tbody>${filtered.map(r=>`<tr><td><strong>${r.id} · ${r.title}</strong><span class="cell-sub">${r.scope} · ${r.source}</span></td><td>${r.category}</td><td><span class="${cls(r.severity)}">${r.severity}</span></td><td>${r.confidence}</td><td>${r.likelihood}×${r.impact}</td><td>${r.owner}</td><td>${r.due}</td><td>${r.status}</td></tr>`).join('')}</tbody></table></div></section>`
}

function decisionCenter() {
  return `<div class="page-heading"><div><div class="eyebrow">DECISION CENTER</div><h1>Needs decision</h1><p>จาก risk และ evidence ไปสู่ action ที่มี owner และ audit trail</p></div><div class="decision-counter"><strong>${decisions.length-state.reviewed.size}</strong><span>pending</span></div></div><div class="decision-grid">${decisions.map(d=>{const p=projects.find(x=>x.id===d.projectId);const done=state.reviewed.has(d.id);return `<article class="decision-card ${done?'done':''}"><div class="decision-top"><span class="${cls(d.severity)}">${d.severity}</span><span>${d.id}</span></div><h2>${d.title}</h2><p>${d.why}</p><div class="decision-project">${p.name}</div><div class="evidence-chips">${d.evidence.map(x=>`<span>${x}</span>`).join('')}</div><div class="recommendation"><small>SYSTEM RECOMMENDATION</small><strong>${d.recommendation}</strong></div><div class="decision-meta"><span>Owner: ${d.owner}</span><span>Due: ${d.due}</span></div><div class="decision-actions"><button class="secondary">ดูหลักฐาน</button><button class="primary" data-review="${d.id}">${done?'Reviewed':'รับทราบ / ส่งต่อ'}</button></div></article>`}).join('')}</div><section class="panel decision-log"><div class="panel-head"><div><h2>Decision log concept</h2><p>MVP แสดงโครงสร้างที่ควรบันทึกเมื่อเชื่อม backend</p></div></div><div class="log-fields"><span>Decision</span><span>Reason</span><span>Decision maker</span><span>Evidence reviewed</span><span>Decision date</span><span>Next review</span></div></section>`
}

function mrvView() {
  const p = projects.find(x=>x.id===state.project) || projects[0]
  const rows = readiness[p.id]
  const ready = rows.filter(r=>r[1]==='Ready').length
  return `<div class="page-heading"><div><div class="eyebrow">MRV READINESS</div><h1>Verification readiness</h1><p>ดูว่า “ยังขาดอะไร” แทนที่จะดูเพียงว่า monitoring complete หรือไม่</p></div></div><div class="toolbar"><select id="mrvProject">${projects.map(x=>`<option value="${x.id}" ${x.id===p.id?'selected':''}>${x.name}</option>`).join('')}</select></div><div class="two-col mrv-layout"><section class="panel readiness-score"><div class="ring" style="--pct:${p.mrv}%"><div><strong>${p.mrv}%</strong><span>MRV readiness</span></div></div><h2>${p.name}</h2><p>${ready}/${rows.length} areas marked Ready in the demo checklist</p><div class="freshness">Latest evidence status: <strong>mixed freshness</strong></div></section><section class="panel"><div class="panel-head"><div><h2>Readiness checklist</h2><p>จาก management layer ลงไปหา source evidence ในระบบจริงภายหลัง</p></div></div><div class="checklist">${rows.map(([name,status,note])=>`<div class="check-row"><span class="check-icon ${status.toLowerCase()}">${status==='Ready'?'✓':status==='Missing'?'×':'!'}</span><div><strong>${name}</strong><span>${note}</span></div><span class="check-status ${status.toLowerCase()}">${status}</span></div>`).join('')}</div></section></div><section class="panel"><div class="panel-head"><div><h2>Readiness vs project timing</h2><p>ใช้ช่วยตอบว่า milestone ถัดไปพร้อมหรือยัง</p></div></div><div class="readiness-summary"><div><small>Next milestone</small><strong>${p.nextMilestone}</strong><span>in ${p.milestoneDays} days</span></div><div><small>Monitoring</small><strong>${p.monitoring}%</strong><span>current cycle</span></div><div><small>Open risks</small><strong>${risks.filter(r=>r.projectId===p.id).length}</strong><span>portfolio register</span></div><div><small>Carbon forecast</small><strong>${Math.round(p.carbonForecast/p.carbonTarget*100)}%</strong><span>of target</span></div></div></section>`
}

function render() {
  const views = { overview, projects:projectsView, risks:riskCenter, decisions:decisionCenter, mrv:mrvView }
  document.getElementById('app').innerHTML = shell(views[state.nav]())
  bind()
}

function bind() {
  document.querySelectorAll('[data-nav]').forEach(el => el.addEventListener('click', () => { state.nav = el.dataset.nav; state.mobile=false; render() }))
  document.querySelectorAll('[data-project]').forEach(el => el.addEventListener('click', () => { state.project=el.dataset.project; state.nav='projects'; render() }))
  document.querySelectorAll('[data-select-project]').forEach(el => el.addEventListener('click', () => { state.project=el.dataset.selectProject; render() }))
  document.querySelectorAll('[data-severity]').forEach(el => el.addEventListener('click', () => { state.severity=el.dataset.severity; render() }))
  document.querySelectorAll('[data-review]').forEach(el => el.addEventListener('click', () => { state.reviewed.add(el.dataset.review); render() }))
  const cat = document.getElementById('category'); if (cat) cat.addEventListener('change', e => { state.category=e.target.value; render() })
  const mrvProject = document.getElementById('mrvProject'); if (mrvProject) mrvProject.addEventListener('change', e => { state.project=e.target.value; render() })
  const menu = document.getElementById('menu'); if (menu) menu.addEventListener('click', () => { state.mobile=!state.mobile; render() })
}

render()
